services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: postgres_rag
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rag
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d rag -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  bootstrap_vector_ext:
    image: pgvector/pgvector:pg17
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      PGPASSWORD: postgres
    entrypoint: ["/bin/sh", "-ec"]
    command: |
      echo "[bootstrap] aguardando Postgres..."
      until psql -h postgres -p 5432 -U postgres -d rag -c "select 1" >/dev/null 2>&1; do
        sleep 2
      done
      echo "[bootstrap] criando extensão vector..."
      psql -h postgres -p 5432 -U postgres -d rag -v ON_ERROR_STOP=1 \
        -c "CREATE EXTENSION IF NOT EXISTS vector;"
      echo "[bootstrap] OK"
    restart: "no"

volumes:
  postgres_data:
